version: "3.8"

services:

  cards-front:
    image: front:1.0
    ports:
      - '3000:80'

  gateway:
    image: gateway:0.0.1-SNAPSHOT
    ports:
      - '8000:8000'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
    depends_on:
      - rabbitmq-dev
      - consul-importer
    networks:
      - micro_card

  recorder:
    image: recorder:0.0.1-SNAPSHOT
    ports:
      - '8082:8082'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_CONSUL_HOST=consul
    depends_on:
      - rabbitmq-dev
      - consul-importer
    networks:
      - micro_card

  resolver-2:
    image: resolver:0.0.1-SNAPSHOT
    ports:
      - '8085:8085'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_CONSUL_HOST=consul
    depends_on:
      - consul-importer
    networks:
      - micro_card

  resolver-1:
    image: resolver:0.0.1-SNAPSHOT
    ports:
      - '8086:8085'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_CONSUL_HOST=consul
    depends_on:
      - consul-importer
    networks:
      - micro_card

  ongoing:
    image: ongoing:0.0.1-SNAPSHOT
    ports:
      - '8081:8081'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_CONSUL_HOST=consul
    depends_on:
      - consul-importer
      - rabbitmq-dev
    networks:
      - micro_card

  rabbitmq-dev:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - micro_card

  consul-dev:
    image: hashicorp/consul:1.19.2
    container_name: consul
    ports:
      - '8500:8500'
    command: 'agent -dev -node=cards -client=0.0.0.0 -log-level=INFO'
    networks:
      - micro_card

  consul-importer:
    image: consul-importer:1.19.2
    depends_on:
      - consul-dev
    networks:
      - micro_card

networks:
  micro_card:
    driver: bridge